/*
 * QVirt-Manager
 *
 * Copyright (C) 2025-2026 Inoki <veyx.shaw@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#include "FirmwareDialog.h"
#include <QVBoxLayout>
#include <QFormLayout>
#include <QHBoxLayout>
#include <QFileDialog>
#include <QMessageBox>

namespace QVirt {

FirmwareDialog::FirmwareDialog(Domain *domain, QWidget *parent)
    : QDialog(parent)
    , m_domain(domain)
{
    setWindowTitle(tr("Firmware Configuration"));
    setModal(true);
    setMinimumWidth(500);
    
    setupUI();
    loadSettings();
}

void FirmwareDialog::setupUI()
{
    auto *mainLayout = new QVBoxLayout(this);

    // Firmware type group
    m_firmwareGroup = new QGroupBox(tr("Firmware Type"), this);
    auto *firmwareLayout = new QVBoxLayout(m_firmwareGroup);

    m_firmwareTypeCombo = new QComboBox(this);
    m_firmwareTypeCombo->addItem(tr("BIOS (SeaBIOS)"), "bios");
    m_firmwareTypeCombo->addItem(tr("UEFI (OVMF)"), "uefi");
    m_firmwareTypeCombo->addItem(tr("UEFI with Secure Boot"), "uefi-secure");
    m_firmwareTypeCombo->addItem(tr("Custom Firmware"), "custom");
    connect(m_firmwareTypeCombo, QOverload<int>::of(&QComboBox::currentIndexChanged),
            this, &FirmwareDialog::onFirmwareTypeChanged);
    firmwareLayout->addWidget(m_firmwareTypeCombo);

    m_firmwareInfoLabel = new QLabel(this);
    m_firmwareInfoLabel->setWordWrap(true);
    m_firmwareInfoLabel->setStyleSheet("color: #666; margin-top: 5px;");
    firmwareLayout->addWidget(m_firmwareInfoLabel);

    mainLayout->addWidget(m_firmwareGroup);

    // Secure Boot group
    auto *secureBootGroup = new QGroupBox(tr("Secure Boot"), this);
    auto *secureBootLayout = new QFormLayout(secureBootGroup);

    m_secureBootCheck = new QCheckBox(tr("Enable Secure Boot"), this);
    connect(m_secureBootCheck, &QCheckBox::toggled, this, &FirmwareDialog::onSecureBootToggled);
    secureBootLayout->addRow(m_secureBootCheck);

    m_secureBootTemplateCombo = new QComboBox(this);
    m_secureBootTemplateCombo->addItem(tr("Microsoft Windows"), "microsoft");
    m_secureBootTemplateCombo->addItem(tr("Microsoft 3rd Party UEFI CA"), "microsoft-3rd-party");
    m_secureBootTemplateCombo->addItem(tr("UEFI Certificate Authority"), "uefi-ca");
    m_secureBootTemplateCombo->setEnabled(false);
    secureBootLayout->addRow(tr("Template:"), m_secureBootTemplateCombo);

    mainLayout->addWidget(secureBootGroup);

    // NVRAM path
    auto *nvramGroup = new QGroupBox(tr("NVRAM Store"), this);
    auto *nvramLayout = new QFormLayout(nvramGroup);

    auto *nvramPathLayout = new QHBoxLayout();
    m_nvramPathEdit = new QLineEdit(this);
    m_nvramPathEdit->setPlaceholderText(tr("Auto-generated by libvirt"));
    nvramPathLayout->addWidget(m_nvramPathEdit);

    m_nvramBrowseBtn = new QPushButton(tr("Browse..."), this);
    connect(m_nvramBrowseBtn, &QPushButton::clicked, this, &FirmwareDialog::onBrowseNvram);
    nvramPathLayout->addWidget(m_nvramBrowseBtn);

    nvramLayout->addRow(tr("Path:"), nvramPathLayout);

    auto *nvramInfoLabel = new QLabel(
        tr("NVRAM stores UEFI variables. Leave empty for auto-generation."), this);
    nvramInfoLabel->setWordWrap(true);
    nvramInfoLabel->setStyleSheet("color: #666; font-size: 11px;");
    nvramLayout->addRow(nvramInfoLabel);

    mainLayout->addWidget(nvramGroup);

    // Button box
    m_buttonBox = new QDialogButtonBox(
        QDialogButtonBox::Ok | QDialogButtonBox::Cancel | QDialogButtonBox::RestoreDefaults,
        this);
    connect(m_buttonBox, &QDialogButtonBox::accepted, this, [this]() {
        saveSettings();
        accept();
    });
    connect(m_buttonBox, &QDialogButtonBox::rejected, this, &QDialog::reject);
    connect(m_buttonBox, &QDialogButtonBox::clicked, this, [this](QAbstractButton *btn) {
        if (m_buttonBox->buttonRole(btn) == QDialogButtonBox::ResetRole) {
            loadSettings();
        }
    });
    mainLayout->addWidget(m_buttonBox);
}

void FirmwareDialog::loadSettings()
{
    if (!m_domain) return;

    QString xml = m_domain->getXMLDesc(0);
    
    // Parse firmware type from XML
    if (xml.contains("type='efi'") || xml.contains("<firmware")) {
        if (xml.contains("secureBoot='yes'")) {
            m_firmwareTypeCombo->setCurrentIndex(2); // UEFI with Secure Boot
        } else {
            m_firmwareTypeCombo->setCurrentIndex(1); // UEFI
        }
    } else {
        m_firmwareTypeCombo->setCurrentIndex(0); // BIOS
    }

    // Parse Secure Boot template
    if (xml.contains("template=")) {
        int templateIdx = xml.indexOf("template='");
        if (templateIdx > 0) {
            int start = templateIdx + 10;
            int end = xml.indexOf("'", start);
            if (end > start) {
                QString tmpl = xml.mid(start, end - start);
                for (int i = 0; i < m_secureBootTemplateCombo->count(); i++) {
                    if (m_secureBootTemplateCombo->itemData(i).toString() == tmpl) {
                        m_secureBootTemplateCombo->setCurrentIndex(i);
                        break;
                    }
                }
            }
        }
    }

    // Parse NVRAM path
    int nvramIdx = xml.indexOf("nvram='");
    if (nvramIdx > 0) {
        int start = nvramIdx + 7;
        int end = xml.indexOf("'", start);
        if (end > start) {
            m_nvramPathEdit->setText(xml.mid(start, end - start));
        }
    }

    onFirmwareTypeChanged(m_firmwareTypeCombo->currentIndex());
}

void FirmwareDialog::saveSettings()
{
    if (!m_domain) return;

    // Get current XML
    QString xml = m_domain->getXMLDesc(0);
    
    // Note: Full implementation would modify the domain XML
    // This is a simplified version that shows the configuration
    QMessageBox::information(this, tr("Firmware Configuration"),
        tr("Firmware settings configured.\n\n"
           "Note: Full firmware configuration requires domain XML modification.\n"
           "Changes will be applied on next VM restart."));
}

void FirmwareDialog::onFirmwareTypeChanged(int index)
{
    QString info;
    bool secureBootEnabled = (index == 2);
    
    switch (index) {
    case 0: // BIOS
        info = tr("SeaBIOS - Traditional BIOS firmware. Compatible with most operating systems.");
        break;
    case 1: // UEFI
        info = tr("OVMF - UEFI firmware without Secure Boot. Required for some modern OS features.");
        break;
    case 2: // UEFI with Secure Boot
        info = tr("UEFI with Secure Boot - Enhanced security. Required for Windows 11 and some Linux distributions.");
        break;
    case 3: // Custom
        info = tr("Custom firmware - Specify custom firmware path in advanced settings.");
        break;
    }
    
    m_firmwareInfoLabel->setText(info);
    m_secureBootCheck->setChecked(secureBootEnabled);
    m_secureBootTemplateCombo->setEnabled(secureBootEnabled);
}

void FirmwareDialog::onSecureBootToggled(bool checked)
{
    if (checked && m_firmwareTypeCombo->currentIndex() != 2) {
        m_firmwareTypeCombo->setCurrentIndex(2);
    }
}

void FirmwareDialog::onBrowseNvram()
{
    QString path = QFileDialog::getSaveFileName(this, tr("Select NVRAM Path"),
        m_nvramPathEdit->text(), tr("NVRAM Files (*)"));
    if (!path.isEmpty()) {
        m_nvramPathEdit->setText(path);
    }
}

} // namespace QVirt
